# Generated by Django 6.0.1 on 2026-02-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('imagen', models.ImageField(upload_to='blog/', verbose_name='Foto Principal')),
                ('contenido', models.TextField(verbose_name='Contenido del Artículo')),
                ('fecha_publicacion', models.DateField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Artículo del Blog',
                'verbose_name_plural': 'Blog - Noticias',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(upload_to='blog/')),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaAliada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='aliados/')),
                ('enlace', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion_corta', models.CharField(help_text='Texto corto para la tarjeta del inicio', max_length=200)),
                ('imagen', models.ImageField(upload_to='servicios/')),
                ('enlace_html', models.CharField(default='hospedaje.html', help_text='Nombre del archivo HTML al que lleva (ej: hospedaje.html)', max_length=50)),
                ('orden', models.IntegerField(default=0, help_text='Número para ordenar (1 sale primero, 2 segundo...)')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios del Inicio',
                'ordering': ['orden'],
            },
        ),
    ]
